name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Force reset local branch to match Hugging Face
        run: git reset --hard https://MLOps-J-A-E:$HF_TOKEN@huggingface.co/spaces/MLOps-J-A-E/J-A-E-Chatbot main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://MLOps-J-A-E:$HF_TOKEN@huggingface.co/spaces/MLOps-J-A-E/J-A-E-Chatbot main